# Generated by Django 5.2.3 on 2025-07-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('CRITIC', 'Critic'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Admin')], default='USER', max_length=50),
        ),
    ]
