# Generated by Django 5.2.3 on 2025-07-01 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('original_title', models.TextField()),
                ('video', models.BooleanField(default=False)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True)),
                ('imdb_id', models.TextField(blank=True)),
                ('tagline', models.TextField(blank=True)),
                ('homepage', models.URLField(blank=True, max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('release_date', models.DateField(blank=True, null=True)),
                ('original_language', models.CharField(blank=True, max_length=10)),
                ('poster_path', models.TextField(blank=True)),
                ('backdrop_path', models.TextField(blank=True)),
                ('genres', models.JSONField(blank=True, null=True)),
                ('genres_names', models.TextField(blank=True)),
                ('origin_country', models.JSONField(blank=True, null=True)),
                ('spoken_languages', models.JSONField(blank=True, null=True)),
                ('spoken_languages_names', models.TextField(blank=True)),
                ('production_companies', models.JSONField(blank=True, null=True)),
                ('production_companies_names', models.TextField(blank=True)),
                ('production_countries', models.JSONField(blank=True, null=True)),
                ('production_countries_names', models.TextField(blank=True)),
                ('collection_id', models.IntegerField(blank=True, null=True)),
                ('collection_name', models.TextField(blank=True)),
                ('collection_poster_path', models.TextField(blank=True)),
                ('collection_backdrop_path', models.TextField(blank=True)),
                ('external_imdb_id', models.TextField(blank=True)),
                ('external_twitter_id', models.TextField(blank=True)),
                ('external_facebook_id', models.TextField(blank=True)),
                ('external_wikidata_id', models.TextField(blank=True)),
                ('external_instagram_id', models.TextField(blank=True)),
                ('videos', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='backend_api_title_62622a_idx'), models.Index(fields=['release_date'], name='backend_api_release_5bd511_idx'), models.Index(fields=['vote_average'], name='backend_api_vote_av_1e6364_idx'), models.Index(fields=['popularity'], name='backend_api_popular_a1fe47_idx')],
            },
        ),
    ]
