# Generated by Django 5.2.3 on 2025-07-02 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('tmdb_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OriginCountry',
            fields=[
                ('iso_3166_1', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('tmdb_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('origin_country', models.CharField(blank=True, max_length=5, null=True)),
                ('logo_path', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductionCountry',
            fields=[
                ('iso_3166_1', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('iso_639_1', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('english_name', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('english_name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=30)),
                ('size', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=50)),
                ('official', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('-published_at',),
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres_names',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='origin_country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_companies_names',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_countries_names',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='spoken_languages_names',
        ),
        migrations.AlterField(
            model_name='movie',
            name='external_facebook_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='external_imdb_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='external_instagram_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='external_twitter_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='external_wikidata_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_companies',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_countries',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='spoken_languages',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='videos',
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.movie')),
            ],
            options={
                'unique_together': {('movie', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='MovieOriginCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.movie')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.origincountry')),
            ],
            options={
                'unique_together': {('movie', 'country')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='origin_countries',
            field=models.ManyToManyField(related_name='movies', through='backend_api.MovieOriginCountry', to='backend_api.origincountry'),
        ),
        migrations.CreateModel(
            name='MovieProductionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.movie')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.productioncompany')),
            ],
            options={
                'unique_together': {('movie', 'company')},
            },
        ),
        migrations.CreateModel(
            name='MovieProductionCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.movie')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.productioncountry')),
            ],
            options={
                'unique_together': {('movie', 'country')},
            },
        ),
        migrations.CreateModel(
            name='MovieSpokenLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.movie')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.spokenlanguage')),
            ],
            options={
                'unique_together': {('movie', 'language')},
            },
        ),
        migrations.CreateModel(
            name='MovieVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.movie')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.video')),
            ],
            options={
                'unique_together': {('movie', 'video')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', through='backend_api.MovieGenre', to='backend_api.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=models.ManyToManyField(related_name='movies', through='backend_api.MovieProductionCompany', to='backend_api.productioncompany'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_countries',
            field=models.ManyToManyField(related_name='movies', through='backend_api.MovieProductionCountry', to='backend_api.productioncountry'),
        ),
        migrations.AddField(
            model_name='movie',
            name='spoken_languages',
            field=models.ManyToManyField(related_name='movies', through='backend_api.MovieSpokenLanguage', to='backend_api.spokenlanguage'),
        ),
        migrations.AddField(
            model_name='movie',
            name='videos',
            field=models.ManyToManyField(related_name='movies', through='backend_api.MovieVideo', to='backend_api.video'),
        ),
    ]
