# Generated by Django 5.2.3 on 2025-07-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_genre_origincountry_productioncompany_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncompany',
            name='logo_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spokenlanguage',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='official',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
