# Generated by Django 5.2.3 on 2025-07-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_alter_movie_imdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='adult',
        ),
    ]
