# Generated by Django 5.2.3 on 2025-07-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewreport',
            options={'ordering': ['-created_at']},
        ),
    ]
