# Generated by Django 5.2.3 on 2025-07-08 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviewreport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewvote',
            options={'ordering': ['-created_at']},
        ),
    ]
