# Generated by Django 5.2.3 on 2025-07-07 02:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend_api', '0006_remove_movie_adult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.movie')),
                ('movie_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.movielist')),
            ],
            options={
                'ordering': ['order', 'added_at'],
                'unique_together': {('movie_list', 'movie')},
            },
        ),
        migrations.AddField(
            model_name='movielist',
            name='movies',
            field=models.ManyToManyField(related_name='custom_lists', through='catalog.MovieListItem', to='backend_api.movie'),
        ),
        migrations.AlterUniqueTogether(
            name='movielist',
            unique_together={('user', 'name')},
        ),
        migrations.CreateModel(
            name='UserMovieCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('bookmarked', 'Bookmarked'), ('watched', 'Watched'), ('want_to_watch', 'Want to Watch')], max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('watched_at', models.DateTimeField(blank=True, null=True)),
                ('personal_rating', models.FloatField(blank=True, help_text='Personal rating from 0.0 to 10.0', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('notes', models.TextField(blank=True, help_text='Personal notes about the movie')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_catalog', to='backend_api.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_catalog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='catalog_use_user_id_5d4970_idx'), models.Index(fields=['user', 'added_at'], name='catalog_use_user_id_01f152_idx'), models.Index(fields=['movie', 'status'], name='catalog_use_movie_i_ad095f_idx')],
                'unique_together': {('user', 'movie', 'status')},
            },
        ),
    ]
